config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "flights#index"
  resources :flights
  resources :bookings
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, foreign_key: :departure_airport_id, class_name: "Flight", dependent: :destroy
    has_many :arriving_flights, foreign_key: :arrival_airport_id, class_name: "Flight", dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :flight 
    has_many :passengers, dependent: :destroy
    accepts_nested_attributes_for :passengers, allow_destroy: true

    def as_json(options={})
        {:id => self.id,
         :passengers => self.passengers
        }
    end 
end

app/models/flight.rb
require 'date'
class Flight < ApplicationRecord
    belongs_to :departure_airport, class_name: "Airport"
    belongs_to :arrival_airport, class_name: "Airport"
    has_many :bookings, dependent: :destroy

    def as_json(_options={})
        { :id => self.id }
    end 

    def self.search(param1,param2,param3)
        if param1
            self.where(departure_airport_id: param1, arrival_airport_id: param2, date: param3)
        else
            Flight.all
        end
    end

end

app/models/passenger.rb
class Passenger < ApplicationRecord
    belongs_to :booking
    validates :name, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

    
    def index
        @bookings = Booking.all

        respond_to do |format|
            format.html
            format.json { render :json => @bookings }
        end
    end

    def new
        @booking = Booking.new
        @flight = Flight.find_by(id: params[:flight_id])
        @flight.number_of_passengers = params[:number_of_passengers]
        @flight.number_of_passengers.times { @booking.passengers.build }
    end

    def show
        @booking = Booking.find(params[:id])
    end

    def create
        @flight = Flight.find( params[:booking][:flight_id] )
        @booking = @flight.bookings.build(booking_params)

        if @booking.save
            @booking.passengers.each do |passenger|
                PassengerMailer.with( passenger: passenger).welcome_email.deliver_later
            end

            redirect_to booking_path(@booking) ,notice: "You successfully booked your tickets"
        else
            render :new, status: :unprocessable_entity
        end
    end

    

    def booking_params
        params.require(:booking).permit(:flight_id,passengers_attributes: [:name,:email,:_destroy])
    end


end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    def index
        @flights = Flight.search(params[:departure_airport_id],params[:arrival_airport_id],params[:date])
        @airport_options = Airport.all.map {|a| [a.code,a.id]}
        @number_options = [[1],[2],[3],[4]]
        @dates_options = (Date.today..Date.today+20).map {|date| [date]}

        respond_to do |format|
            format.html
            format.json { render :json => @flights, include: :airports }
        end
    end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
    def new
        @passenger = Passenger.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/_passenger_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <button type="button" data-action="nested-form#remove">Remove passenger</button>

  <%= f.hidden_field :_destroy %>
</div>

app/views/bookings/new.html.erb
<h1> Book your flight </h1>

<%= form_with model: @booking do |f|%>
    <div>
        <%= f.hidden_field :flight_id, value: "#{@flight.id}"%>
    </div>
    <div>
        <strong>Departure Airport: </strong>
        <%= @flight.departure_airport.code %>
    </div>
    <div>
        <strong>Arrival Airport: </strong>
        <%= @flight.arrival_airport.code %>
    </div>
    <div>
        <strong>Departure date: </strong>
        <%= @flight.date %>
    </div>
    <div>
        <strong>Departure time: </strong>
        <%= @flight.time.strftime("%H:%m") %>
    </div>
    <div>
        <strong>Flight duration: </strong>
        <%= @flight.duration %>
    </div>
    <div>
        <strong>Number of passengers: </strong>
        <%= @flight.number_of_passengers %>
    </div><br>

    <%= f.fields_for :passengers do |passengers_form|%>
        <div><%= passengers_form.label :name %>
        <%= passengers_form.text_field :name%></div>

        <div><%= passengers_form.label :email %>
        <%= passengers_form.email_field :email%></div><br>
    <% end %>

    <%= f.submit "Book"%>
<% end %>

app/views/bookings/show.html.erb
<h1> Here is your info </h1>

<h2> Booking information </h2>
    <div>
        <strong>Departure Airport: </strong>
        <%= @booking.flight.departure_airport.code %>
    </div>
    <div>
        <strong>Arrival Airport: </strong>
        <%= @booking.flight.arrival_airport.code %>
    </div>
    <div>
        <strong>Departure date: </strong>
        <%= @booking.flight.date %>
    </div>
    <div>
        <strong>Departure time: </strong>
        <%= @booking.flight.time.strftime("%H:%m") %>
    </div>
    <div>
        <strong>Flight duration: </strong>
        <%= @booking.flight.duration %>
    </div><br>

<h2> Passengers information </h2>
    <% @booking.passengers.each do |p|%>
        <div><strong>Name: </strong>
        <%= p.name %></div>
        <div><strong>Email: </strong>
        <%= p.email %></div><br>
    <% end %>

<%= link_to  "Back to home page", flights_path%>

app/views/flights/index.html.erb
<h1> Flights </h1>

<% if @flights.size == Flight.all.size %>
    <% flights = @flights.first(5) %>
    <% flights.each do |flight|%>
        <ul>
                <li><%= flight.date %></li>
                <div><%= flight.time.strftime("%H:%m") %></div>
                <div><%= flight.duration %></div>
                <div><%= flight.departure_airport.code %></div>
                <div><%= flight.arrival_airport.code %></div>
        </ul>
    <% end %>
<% else %>
    <% @flights.each do |flight|%>
        <% flight.number_of_passengers = params[:number_of_passengers]%>
        <ul>
                <li><strong>Date:</strong> <%=  flight.date %></li>
                <div><strong>Departure time:</strong> <%= flight.time.strftime("%H:%m") %></div>
                <div><strong>Flight duration:</strong> <%= flight.duration %></div>
                <div><strong>Departure airport:</strong> <%= flight.departure_airport.code %></div>
                <div><strong>Arrival airport:</strong> <%= flight.arrival_airport.code %></div>
                <div><strong>Number of passengers:</strong> <%= flight.number_of_passengers %></div>
        </ul>
        <%= form_with url: "/bookings/new", method: :get do |f|%>
                <%= f.label :flight_id, "Book this flight" %>
                <%= f.radio_button :flight_id, "#{flight.id}" %> 
                <%= f.hidden_field :number_of_passengers, value: "#{flight.number_of_passengers}"%>
                <%= f.hidden_field :departure_airport, value: "#{flight.departure_airport_id}"%>
                <%= f.hidden_field :arrival_airport, value: "#{flight.arrival_airport_id}"%>
                <%= f.hidden_field :date, value: "#{flight.date}"%>
                <%= f.hidden_field :time, value: "#{flight.time}"%>
                <%= f.hidden_field :duration, value: "#{flight.duration}"%>
                <%= f.submit "Book" %>
        <% end %>
    <% end %>
<% end %>



<%= form_with url: "/flights", method: :get do |f|%>
    <%= f.select :departure_airport_id, @airport_options %>
    <%= f.select :arrival_airport_id, @airport_options %>
    <%= f.select :number_of_passengers, @number_options %>
    <%= f.select :date, @dates_options%>
    <%= f.submit "Search" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |t,m|%>
      <div><%= m %></div>
    <% end %>
  </body>
</html>